### PR TITLE
Update to new API

### PR DESCRIPTION
**Pull request by mcvova**
fix empty screen

### CODE REVIEW

**Comment by jangtrinh** [comment]
Did the author merge this to the repo yet?

**Comment by dexterbui** [comment]
Could you please merge it to repo?

**Comment by mcvova** [comment]
I don`t have write access to merge. This is fixed plugin: https://drive.google.com/open?id=1lvXovbywHYzWjfi08MQUm2hHDkhlR4X6

**Review by JWhiteUX — COMMENTED** [review]
Please merge this. Lots of people are having trouble with this plugin and don't know how to make the changes to `myScript` — Confirmed, these changes DO WORK

**Comment by Log1x** [comment]
This works great. Merge away!

**Comment by design4use** [comment]
I added similar changes to 2.07. Thanks @mcvova for the contribution - should be working well in 53 now!

**Pull request closed without merging**
